import { Proyek, User, AuditLog } from '@/types'

export const DUMMY_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ir. Ahmad Fauzi, MT',
    email: 'ppk@dumai.go.id',
    role: 'ppk',
    nip: '197605152003121005',
    jabatan: 'Pejabat Pembuat Komitmen',
  },
  {
    id: 'u2',
    name: 'Drs. Bambang Susilo',
    email: 'pimpinan@dumai.go.id',
    role: 'pimpinan',
    nip: '196809201995031002',
    jabatan: 'Kepala Dinas PU',
  },
  {
    id: 'u3',
    name: 'Siti Rahmawati, ST',
    email: 'pptk1@dumai.go.id',
    role: 'pptk',
    nip: '198803042012122001',
    jabatan: 'PPTK Drainase',
  },
  {
    id: 'u4',
    name: 'Rudi Hartono, ST',
    email: 'pptk2@dumai.go.id',
    role: 'pptk',
    nip: '199001152015031003',
    jabatan: 'PPTK Jalan',
  },
  {
    id: 'u5',
    name: 'Tim Perencanaan A',
    email: 'perencanaan@dumai.go.id',
    role: 'tim_perencanaan',
    nip: '199205062017041002',
    jabatan: 'Staf Perencanaan',
  },
  {
    id: 'u6',
    name: 'Tim Pengawasan B',
    email: 'pengawasan@dumai.go.id',
    role: 'tim_pengawasan',
    nip: '199108152018022001',
    jabatan: 'Pengawas Lapangan',
  },
  {
    id: 'u7',
    name: 'CV. Konsultan Mitra Riau',
    email: 'konsultan.perencana@mitra.com',
    role: 'konsultan_perencana',
    jabatan: 'Konsultan Perencana',
  },
  {
    id: 'u8',
    name: 'PT. Pengawas Prima',
    email: 'konsultan.pengawasan@prima.com',
    role: 'konsultan_pengawasan',
    jabatan: 'Konsultan Pengawasan',
  },
  {
    id: 'u9',
    name: 'Admin Sistem',
    email: 'admin@dumai.go.id',
    role: 'admin',
    jabatan: 'Administrator',
  },
]

export const USER_CREDENTIALS: Record<string, { password: string; userId: string }> = {
  'admin@dumai.go.id': { password: 'admin123', userId: 'u9' },
  'ppk@dumai.go.id': { password: 'ppk123', userId: 'u1' },
  'pimpinan@dumai.go.id': { password: 'pimpinan123', userId: 'u2' },
  'pptk1@dumai.go.id': { password: 'pptk123', userId: 'u3' },
  'pptk2@dumai.go.id': { password: 'pptk123', userId: 'u4' },
  'perencanaan@dumai.go.id': { password: 'plan123', userId: 'u5' },
  'pengawasan@dumai.go.id': { password: 'watch123', userId: 'u6' },
  'konsultan.perencana@mitra.com': { password: 'konsultan123', userId: 'u7' },
  'konsultan.pengawasan@prima.com': { password: 'konsultan123', userId: 'u8' },
}

export const DUMMY_PROJECTS: Proyek[] = [
  {
    id: 'p1',
    kode: 'PU-DRN-001/2026',
    nama: 'Rehabilitasi Drainase Jl. Sultan Syarif Kasim',
    lokasi: 'Jl. Sultan Syarif Kasim, Kel. Ratu Sima',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6781, lng: 101.4473 },
    anggaran: 2_850_000_000,
    nilaiKontrak: 2_750_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    health: 'on_track',
    progressFisik: 65,
    progressKeuangan: 58,
    deviasi: -7,
    tanggalMulai: '2026-02-01',
    tanggalSelesai: '2026-07-31',
    kontraktor: 'PT. Bangun Riau Jaya',
    konsultanPerencana: 'CV. Konsultan Mitra Riau',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [
      {
        id: 's1',
        proyekId: 'p1',
        tanggal: '2026-01-15',
        userId: 'u5',
        userName: 'Tim Perencanaan A',
        koordinat: { lat: 1.6781, lng: 101.4473 },
        kondisiEksisting: 'Drainase eksisting kondisi rusak berat, banyak sedimentasi dan vegetasi liar. Kapasitas tampung sangat berkurang akibat penyempitan. Dinding saluran retak dan sebagian ambruk.',
        dimensi: { panjang: 850, lebar: 1.2, tinggi: 1.0 },
        material: 'Beton bertulang K-250, pasangan batu kali 1:4',
        permasalahan: 'Banjir rutin saat hujan >30mm/jam, genangan mencapai 60cm di badan jalan. Warga mengeluh sejak 3 tahun terakhir. Ada 2 titik ambruk kritis.',
        rekomendasi: 'Normalisasi saluran, perbaikan dinding, pemasangan tutup U-ditch precast',
        foto: [
          { id: 'f1', url: '/uploads/survey-p1-1.jpg', uploadedAt: '2026-01-15T09:30:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi eksisting titik 1' },
          { id: 'f2', url: '/uploads/survey-p1-2.jpg', uploadedAt: '2026-01-15T09:45:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Titik ambruk kritis' },
          { id: 'f3', url: '/uploads/survey-p1-3.jpg', uploadedAt: '2026-01-15T10:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi sekitar permukiman' },
        ],
        status: 'submitted',
        createdAt: '2026-01-15T09:00:00',
      },
    ],
    rabList: [
      {
        id: 'rab1',
        proyekId: 'p1',
        versi: 'v1',
        versionNumber: 1,
        items: [
          { no: '1', uraian: 'Pekerjaan Persiapan', satuan: 'Ls', volume: 1, hargaSatuan: 45_000_000, total: 45_000_000 },
          { no: '2', uraian: 'Galian Saluran', satuan: 'm³', volume: 1020, hargaSatuan: 85_000, total: 86_700_000 },
          { no: '3', uraian: 'Pasangan Batu Kali 1:4', satuan: 'm³', volume: 510, hargaSatuan: 850_000, total: 433_500_000 },
          { no: '4', uraian: 'Beton K-250 Dinding', satuan: 'm³', volume: 204, hargaSatuan: 1_250_000, total: 255_000_000 },
          { no: '5', uraian: 'U-Ditch Precast 120x120', satuan: 'unit', volume: 850, hargaSatuan: 1_850_000, total: 1_572_500_000 },
          { no: '6', uraian: 'Pekerjaan Akhir', satuan: 'Ls', volume: 1, hargaSatuan: 357_300_000, total: 357_300_000 },
        ],
        totalAnggaran: 2_750_000_000,
        uploadedBy: 'CV. Konsultan Mitra Riau',
        uploadedAt: '2026-01-20T10:00:00',
        status: 'approved',
      },
    ],
    laporanHarian: [
      {
        id: 'lh1',
        proyekId: 'p1',
        tanggal: '2026-04-26',
        userId: 'u3',
        userName: 'Siti Rahmawati, ST',
        uraianPekerjaan: 'Pemasangan U-Ditch precast STA 0+250 s/d 0+310. Total 60 unit terpasang hari ini. Pekerjaan galian lanjutan STA 0+310 s/d 0+380 sebanyak 84 m³.',
        progressFisik: 65,
        progressKumulatif: 65,
        cuaca: 'berawan',
        koordinat: { lat: 1.6781, lng: 101.4473 },
        foto: [
          { id: 'fl1', url: '/uploads/laporan-p1-1.jpg', uploadedAt: '2026-04-26T08:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Foto pagi - kondisi awal' },
          { id: 'fl2', url: '/uploads/laporan-p1-2.jpg', uploadedAt: '2026-04-26T12:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Pemasangan U-Ditch' },
          { id: 'fl3', url: '/uploads/laporan-p1-3.jpg', uploadedAt: '2026-04-26T16:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Foto sore - kemajuan harian' },
        ],
        disetujui: true,
        disetujuiOleh: 'Ir. Ahmad Fauzi, MT',
        createdAt: '2026-04-26T07:30:00',
      },
    ],
    catatanPengawasan: [
      {
        id: 'cp1',
        proyekId: 'p1',
        userId: 'u6',
        userName: 'Tim Pengawasan B',
        deskripsi: 'Pemasangan U-Ditch sudah sesuai spesifikasi teknis. Sambungan antar unit rapi dan waterproofing sudah diaplikasikan.',
        rekomendasi: 'Lanjutkan pemasangan. Pastikan elevasi sesuai dengan gambar desain pada STA berikutnya.',
        status: 'sesuai',
        foto: [],
        tanggal: '2026-04-26',
        createdAt: '2026-04-26T14:00:00',
      },
    ],
    masalah: [],
    chat: [
      {
        id: 'ch1',
        proyekId: 'p1',
        userId: 'u3',
        userName: 'Siti Rahmawati',
        userRole: 'pptk',
        message: 'Progress hari ini berjalan lancar. Sudah 60 unit U-Ditch terpasang.',
        timestamp: '2026-04-26T16:30:00',
        type: 'text',
      },
      {
        id: 'ch2',
        proyekId: 'p1',
        userId: 'u1',
        userName: 'Ir. Ahmad Fauzi',
        userRole: 'ppk',
        message: 'Bagus. Pastikan kualitas sambungan dicek sebelum timbunan dilaksanakan.',
        timestamp: '2026-04-26T16:45:00',
        type: 'text',
      },
    ],
    assignedUsers: ['u1', 'u3', 'u6', 'u7', 'u8'],
    createdAt: '2026-01-10T08:00:00',
    updatedAt: '2026-04-26T16:30:00',
  },
  {
    id: 'p2',
    kode: 'PU-JLN-002/2026',
    nama: 'Peningkatan Jalan Soekarno Hatta Segmen II',
    lokasi: 'Jl. Soekarno Hatta, Kel. Bumi Ayu',
    kecamatan: 'Bukit Kapur',
    koordinat: { lat: 1.6520, lng: 101.4220 },
    anggaran: 5_200_000_000,
    nilaiKontrak: 5_050_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    health: 'kritis',
    progressFisik: 15,
    progressKeuangan: 30,
    deviasi: -15,
    tanggalMulai: '2026-01-15',
    tanggalSelesai: '2026-06-30',
    kontraktor: 'PT. Karya Dumai Mandiri',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [
      {
        id: 's2',
        proyekId: 'p2',
        tanggal: '2025-12-10',
        userId: 'u5',
        userName: 'Tim Perencanaan A',
        koordinat: { lat: 1.6520, lng: 101.4220 },
        kondisiEksisting: 'Jalan aspal eksisting rusak berat. Berlubang di hampir seluruh segmen, lebar efektif hanya 5m dari rencana 7m.',
        dimensi: { panjang: 1200, lebar: 7, tinggi: 0.15 },
        material: 'AC-WC, AC-BC, Lapis Pondasi Agregat Kelas A',
        permasalahan: 'Banyak lubang besar, drainase tepi jalan tersumbat. Konektivitas ke kawasan industri terganggu.',
        foto: [
          { id: 'f4', url: '/uploads/survey-p2-1.jpg', uploadedAt: '2025-12-10T09:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi jalan rusak berat' },
          { id: 'f5', url: '/uploads/survey-p2-2.jpg', uploadedAt: '2025-12-10T09:30:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Lubang-lubang kritis' },
          { id: 'f6', url: '/uploads/survey-p2-3.jpg', uploadedAt: '2025-12-10T10:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Drainase tersumbat' },
        ],
        status: 'submitted',
        createdAt: '2025-12-10T09:00:00',
      },
    ],
    rabList: [
      {
        id: 'rab2',
        proyekId: 'p2',
        versi: 'v1',
        versionNumber: 1,
        items: [
          { no: '1', uraian: 'Mobilisasi & Demobilisasi', satuan: 'Ls', volume: 1, hargaSatuan: 150_000_000, total: 150_000_000 },
          { no: '2', uraian: 'Pekerjaan Tanah & Persiapan', satuan: 'Ls', volume: 1, hargaSatuan: 200_000_000, total: 200_000_000 },
          { no: '3', uraian: 'Lapis Pondasi Agregat Kelas A', satuan: 'm³', volume: 2520, hargaSatuan: 425_000, total: 1_071_000_000 },
          { no: '4', uraian: 'AC-BC Lapis Antara', satuan: 'ton', volume: 1848, hargaSatuan: 1_250_000, total: 2_310_000_000 },
          { no: '5', uraian: 'AC-WC Lapis Aus', satuan: 'ton', volume: 840, hargaSatuan: 1_380_000, total: 1_159_200_000 },
          { no: '6', uraian: 'Drainase Tepi Jalan', satuan: 'm', volume: 2400, hargaSatuan: 66_583, total: 159_800_000 },
        ],
        totalAnggaran: 5_050_000_000,
        uploadedBy: 'CV. Konsultan Mitra Riau',
        uploadedAt: '2025-12-20T10:00:00',
        status: 'approved',
      },
    ],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [
      {
        id: 'm1',
        proyekId: 'p2',
        judul: 'Kontraktor tidak mobilisasi alat berat sesuai jadwal',
        deskripsi: 'Asphalt finisher dan motor grader belum ada di lokasi padahal sudah melewati minggu ke-6 pelaksanaan. Progres fisik sangat jauh di bawah kurva S.',
        status: 'in_progress',
        prioritas: 'kritis',
        dilaporkanOleh: 'u4',
        dilaporkanOlehName: 'Rudi Hartono, ST',
        tanggal: '2026-04-10',
        foto: [],
        createdAt: '2026-04-10T10:00:00',
      },
    ],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u8'],
    createdAt: '2026-01-05T08:00:00',
    updatedAt: '2026-04-26T08:00:00',
  },
  {
    id: 'p3',
    kode: 'PU-DRN-003/2026',
    nama: 'Pembangunan Box Culvert Sei Dumai',
    lokasi: 'Jl. Pattimura, Kel. Jaya Mukti',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.6920, lng: 101.4680 },
    anggaran: 3_100_000_000,
    nilaiKontrak: 2_980_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    health: 'warning',
    progressFisik: 40,
    progressKeuangan: 52,
    deviasi: -12,
    tanggalMulai: '2026-02-15',
    tanggalSelesai: '2026-08-15',
    kontraktor: 'CV. Bersama Maju',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [
      {
        id: 's3',
        proyekId: 'p3',
        tanggal: '2026-01-20',
        userId: 'u5',
        userName: 'Tim Perencanaan A',
        koordinat: { lat: 1.6920, lng: 101.4680 },
        kondisiEksisting: 'Gorong-gorong eksisting berdiameter 80cm sudah tidak mampu menampung debit banjir 10 tahunan. Material besi berkarat.',
        dimensi: { panjang: 120, lebar: 3.0, tinggi: 2.5 },
        material: 'Beton K-300 bertulang, waterproofing membrane',
        permasalahan: 'Banjir tahunan area sekitar, merendam 3 RT. Kapasitas tampung kurang dari 30% kebutuhan.',
        foto: [
          { id: 'f7', url: '/uploads/survey-p3-1.jpg', uploadedAt: '2026-01-20T08:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Gorong-gorong existing' },
          { id: 'f8', url: '/uploads/survey-p3-2.jpg', uploadedAt: '2026-01-20T08:30:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi banjir' },
          { id: 'f9', url: '/uploads/survey-p3-3.jpg', uploadedAt: '2026-01-20T09:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Titik kritis' },
        ],
        status: 'submitted',
        createdAt: '2026-01-20T08:00:00',
      },
    ],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [
      {
        id: 'm2',
        proyekId: 'p3',
        judul: 'Material bekisting tidak sesuai spesifikasi',
        deskripsi: 'Bekisting yang digunakan kontraktor adalah kayu lapis biasa bukan plywood phenol yang disyaratkan, berisiko terhadap kualitas beton.',
        status: 'open',
        prioritas: 'sedang',
        dilaporkanOleh: 'u6',
        dilaporkanOlehName: 'Tim Pengawasan B',
        tanggal: '2026-04-20',
        foto: [],
        createdAt: '2026-04-20T11:00:00',
      },
    ],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6', 'u8'],
    createdAt: '2026-01-10T08:00:00',
    updatedAt: '2026-04-25T14:00:00',
  },
  {
    id: 'p4',
    kode: 'PU-JLN-004/2026',
    nama: 'Peningkatan Jalan Putri Tujuh Segmen I',
    lokasi: 'Jl. Putri Tujuh, Kel. Tanjung Palas',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6850, lng: 101.4390 },
    anggaran: 4_500_000_000,
    nilaiKontrak: 4_350_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    health: 'on_track',
    progressFisik: 45,
    progressKeuangan: 44,
    deviasi: 1,
    tanggalMulai: '2026-03-01',
    tanggalSelesai: '2026-09-30',
    kontraktor: 'PT. Nusa Karya Dumai',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u4'],
    createdAt: '2026-02-20T08:00:00',
    updatedAt: '2026-04-26T08:00:00',
  },
  {
    id: 'p5',
    kode: 'PU-DRN-005/2026',
    nama: 'Normalisasi Parit Sungai Binti',
    lokasi: 'Kawasan Sungai Binti, Kel. Bukit Timah',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.7050, lng: 101.4780 },
    anggaran: 1_800_000_000,
    nilaiKontrak: 1_720_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'rutin',
    health: 'kritis',
    progressFisik: 8,
    progressKeuangan: 20,
    deviasi: -12,
    tanggalMulai: '2026-01-20',
    tanggalSelesai: '2026-05-20',
    kontraktor: 'CV. Sejahtera Riau',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [
      {
        id: 'm3',
        proyekId: 'p5',
        judul: 'Konflik lahan warga belum selesai',
        deskripsi: '3 bidang tanah warga yang terdampak normalisasi belum ada kesepakatan ganti rugi. Kontraktor tidak bisa mulai kerja di area tersebut.',
        status: 'open',
        prioritas: 'kritis',
        dilaporkanOleh: 'u3',
        dilaporkanOlehName: 'Siti Rahmawati, ST',
        tanggal: '2026-02-10',
        foto: [],
        createdAt: '2026-02-10T09:00:00',
      },
    ],
    chat: [],
    assignedUsers: ['u1', 'u3'],
    createdAt: '2026-01-10T08:00:00',
    updatedAt: '2026-04-20T08:00:00',
  },
  {
    id: 'p6',
    kode: 'PU-JLN-006/2026',
    nama: 'Pembangunan Jembatan Sei Mesjid',
    lokasi: 'Jl. Imam Bonjol, Kel. Rimba Sekampung',
    kecamatan: 'Medang Kampai',
    koordinat: { lat: 1.6380, lng: 101.4050 },
    anggaran: 8_500_000_000,
    nilaiKontrak: 8_200_000_000,
    status: 'survey',
    kategoriPekerjaan: 'lelang',
    health: 'warning',
    progressFisik: 22,
    progressKeuangan: 35,
    deviasi: -13,
    tanggalMulai: '2026-02-01',
    tanggalSelesai: '2026-12-31',
    kontraktor: 'PT. Wijaya Karya Tbk',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u4'],
    createdAt: '2026-01-20T08:00:00',
    updatedAt: '2026-04-22T08:00:00',
  },
]

export const DUMMY_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'al1',
    userId: 'u3',
    userName: 'Siti Rahmawati, ST',
    action: 'LOGIN',
    entity: 'auth',
    entityId: 'u3',
    detail: 'Login berhasil dari IP 192.168.1.10',
    ip: '192.168.1.10',
    timestamp: '2026-04-26T07:15:00',
  },
  {
    id: 'al2',
    userId: 'u3',
    userName: 'Siti Rahmawati, ST',
    action: 'UPLOAD_LAPORAN',
    entity: 'laporan_harian',
    entityId: 'lh1',
    detail: 'Upload laporan harian + 3 foto untuk proyek PU-DRN-001/2026',
    ip: '192.168.1.10',
    timestamp: '2026-04-26T07:35:00',
  },
  {
    id: 'al3',
    userId: 'u1',
    userName: 'Ir. Ahmad Fauzi, MT',
    action: 'APPROVE_LAPORAN',
    entity: 'laporan_harian',
    entityId: 'lh1',
    detail: 'Menyetujui laporan harian proyek PU-DRN-001/2026',
    ip: '192.168.1.1',
    timestamp: '2026-04-26T09:00:00',
  },
  {
    id: 'al4',
    userId: 'u6',
    userName: 'Tim Pengawasan B',
    action: 'CREATE_CATATAN',
    entity: 'catatan_pengawasan',
    entityId: 'cp1',
    detail: 'Menambah catatan pengawasan untuk proyek PU-DRN-001/2026',
    ip: '192.168.1.20',
    timestamp: '2026-04-26T14:00:00',
  },
]
