ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'KEPALA_DINAS';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TIM_SURVEYOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'AUDITOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PEJABAT_PENGADAAN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PPHP';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ADMINISTRASI_KONTRAK';
